### ISSUE TITLE
Lios broken on upgrade to Ubuntu 22.10

### ISSUE THREAD

**Issue by thejudderman** [zendalona/lios#21]
I recently discovered your great app! Thank you. 
However, since upgrading to 22.10, lios won't start up. 
Here is the error I get:

`/usr/lib/python3/dist-packages/lios/ui/gtk/text_view.py:21: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib/python3/dist-packages/lios/ui/gtk/widget.py:24: PyGIWarning: Atk was imported without specifying a version first. Use gi.require_version('Atk', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Atk
Traceback (most recent call last):
  File "/usr/bin/lios", line 3, in <module>
    from lios.main import *
  File "/usr/lib/python3/dist-packages/lios/main.py", line 27, in <module>
    from lios import scanner, editor, imageview, cam, ocr, preferences, speech, train_tesseract
  File "/usr/lib/python3/dist-packages/lios/editor.py", line 20, in <module>
    from lios.ui.gtk import text_view, tree_view, widget, dialog, file_chooser, containers, window
  File "/usr/lib/python3/dist-packages/lios/ui/gtk/widget.py", line 166, in <module>
    class Separator(Gtk.HSeparator):
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'HSeparator'
`

Any help would be appreciated - I'm a regular linux user, but not much experience in coding!

**Comment by thejudderman** [comment]
> This was fixed by commit [73fc343](https://github.com/zendalona/lios/commit/73fc343c7929bb385ded53130d842dc5d084bfe3)

Has this commit not been merged to main branch? How do I install this commit? I keep on getting the same error.

Thanks

**Comment by sthibaul** [comment]
It is on the main branch.

**Comment by thejudderman** [comment]
Thank you - I have purged all lios files reinstalled it now from the main branch. It is now working!
